version: '3.8'


services:
  django:
    build: .
    volumes:
    - static:/static
    ports:
      - "8000:8000"
    # networks:
    #   local_network:
    #     ipv4_address: 172.28.1.4
  
  nginx:
    build: ./nginx
    volumes:
      - static:/var/www/static
    ports:
      - "80:80"
    depends_on:
      - django
    # networks:
    #   local_network:
    #     ipv4_address: 172.28.1.3

volumes:
  static:

# networks:
#   local_network:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.0.0/24